import re

path = r'c:\Users\likit\Desktop\PlacementAI\frontend\src\app\auth\page.tsx'
with open(path, 'r', encoding='utf-8') as f:
    content = f.read()

old_theme_vars = """  const themeVars = selectedRole === 'RECRUITER' ? {
    '--auth-bg-gradient': 'linear-gradient(135deg, #4A154B 0%, #2D1B4E 100%)',
    '--auth-logo-color': '#832838',
    '--auth-headline-span': '#F9A8D4',
    '--auth-feature-bg': 'rgba(131, 40, 56, 0.4)',
    '--auth-icon-bg': 'rgba(131, 40, 56, 0.8)',
    '--auth-btn-color': '#832838',
    '--auth-icon-color': '#832838',
    '--auth-icon-bg-light': '#FDF2F8',
    '--auth-focus-ring': 'rgba(131, 40, 56, 0.2)',
    '--auth-primary-btn': 'linear-gradient(to right, #832838, #9D364A)',
    '--auth-primary-shadow': 'rgba(131, 40, 56, 0.5)',
    '--auth-active-tab-bg': '#FDF2F8',
    '--auth-active-tab-text': '#832838',
    '--auth-active-tab-border': '#832838',
    '--auth-headline-size': '32px',
    '--auth-headline-mb': '8px',
    '--auth-desc-size': '13px',
    '--auth-desc-mb': '12px',
    '--auth-features-gap': '6px',
    '--auth-feature-item-gap': '12px',
    '--auth-feature-item-padding': '8px 12px',
    '--auth-icon-size': '32px',
    '--auth-icon-radius': '8px',
    '--auth-svg-size': '16px',
    '--auth-h3-size': '13px',
    '--auth-h3-mb': '2px',
    '--auth-p-size': '11px',
    '--auth-p-lh': '1.3',
  } : {
    '--auth-bg-gradient': 'linear-gradient(135deg, #312e81 0%, #1e1b4b 100%)',
    '--auth-logo-color': '#4338ca',
    '--auth-headline-span': '#d8b4fe',
    '--auth-feature-bg': 'rgba(49, 46, 129, 0.6)',
    '--auth-icon-bg': 'rgba(99, 102, 241, 0.4)',
    '--auth-btn-color': '#4f46e5',
    '--auth-icon-color': '#7e22ce',
    '--auth-icon-bg-light': '#f3e8ff',
    '--auth-focus-ring': 'rgba(168, 85, 247, 0.2)',
    '--auth-primary-btn': 'linear-gradient(to right, #4F46E5, #9333EA, #EC4899)',
    '--auth-primary-shadow': 'rgba(147, 51, 234, 0.5)',
    '--auth-active-tab-bg': '#faf5ff',
    '--auth-active-tab-text': '#7e22ce',
    '--auth-active-tab-border': '#a855f7',
    '--auth-headline-size': '38px',
    '--auth-headline-mb': '12px',
    '--auth-desc-size': '15px',
    '--auth-desc-mb': '16px',
    '--auth-features-gap': '12px',
    '--auth-feature-item-gap': '16px',
    '--auth-feature-item-padding': '16px',
    '--auth-icon-size': '40px',
    '--auth-icon-radius': '12px',
    '--auth-svg-size': '20px',
    '--auth-h3-size': '15px',
    '--auth-h3-mb': '4px',
    '--auth-p-size': '13px',
    '--auth-p-lh': '1.4',
  };"""

new_theme_vars = """  const getThemeVars = () => {
    if (selectedRole === 'RECRUITER') {
      return {
        '--auth-bg-gradient': 'linear-gradient(135deg, #4A154B 0%, #2D1B4E 100%)',
        '--auth-logo-color': '#832838',
        '--auth-headline-span': '#F9A8D4',
        '--auth-feature-bg': 'rgba(131, 40, 56, 0.4)',
        '--auth-icon-bg': 'rgba(131, 40, 56, 0.8)',
        '--auth-btn-color': '#832838',
        '--auth-icon-color': '#832838',
        '--auth-icon-bg-light': '#FDF2F8',
        '--auth-focus-ring': 'rgba(131, 40, 56, 0.2)',
        '--auth-primary-btn': 'linear-gradient(to right, #832838, #9D364A)',
        '--auth-primary-shadow': 'rgba(131, 40, 56, 0.5)',
        '--auth-active-tab-bg': '#FDF2F8',
        '--auth-active-tab-text': '#832838',
        '--auth-active-tab-border': '#832838',
        '--auth-headline-size': '32px',
        '--auth-headline-mb': '8px',
        '--auth-desc-size': '13px',
        '--auth-desc-mb': '12px',
        '--auth-features-gap': '6px',
        '--auth-feature-item-gap': '12px',
        '--auth-feature-item-padding': '8px 12px',
        '--auth-icon-size': '32px',
        '--auth-icon-radius': '8px',
        '--auth-svg-size': '16px',
        '--auth-h3-size': '13px',
        '--auth-h3-mb': '2px',
        '--auth-p-size': '11px',
        '--auth-p-lh': '1.3',
      };
    } else if (selectedRole === 'PLACEMENT_OFFICER') {
      return {
        '--auth-bg-gradient': 'linear-gradient(135deg, #222539 0%, #171827 100%)',
        '--auth-logo-color': '#7B61FF',
        '--auth-headline-span': '#A78BFA',
        '--auth-feature-bg': 'rgba(34, 37, 57, 0.8)',
        '--auth-icon-bg': 'rgba(123, 97, 255, 0.2)',
        '--auth-btn-color': '#7B61FF',
        '--auth-icon-color': '#7B61FF',
        '--auth-icon-bg-light': 'rgba(123, 97, 255, 0.1)',
        '--auth-focus-ring': 'rgba(123, 97, 255, 0.2)',
        '--auth-primary-btn': 'linear-gradient(to right, #6D5DF4, #8873F6)',
        '--auth-primary-shadow': 'rgba(109, 93, 244, 0.5)',
        '--auth-active-tab-bg': '#222539',
        '--auth-active-tab-text': '#7B61FF',
        '--auth-active-tab-border': '#7B61FF',
        '--auth-headline-size': '38px',
        '--auth-headline-mb': '12px',
        '--auth-desc-size': '15px',
        '--auth-desc-mb': '16px',
        '--auth-features-gap': '12px',
        '--auth-feature-item-gap': '16px',
        '--auth-feature-item-padding': '16px',
        '--auth-icon-size': '40px',
        '--auth-icon-radius': '12px',
        '--auth-svg-size': '20px',
        '--auth-h3-size': '15px',
        '--auth-h3-mb': '4px',
        '--auth-p-size': '13px',
        '--auth-p-lh': '1.4',
      };
    } else {
      return {
        '--auth-bg-gradient': 'linear-gradient(135deg, #312e81 0%, #1e1b4b 100%)',
        '--auth-logo-color': '#4338ca',
        '--auth-headline-span': '#d8b4fe',
        '--auth-feature-bg': 'rgba(49, 46, 129, 0.6)',
        '--auth-icon-bg': 'rgba(99, 102, 241, 0.4)',
        '--auth-btn-color': '#4f46e5',
        '--auth-icon-color': '#7e22ce',
        '--auth-icon-bg-light': '#f3e8ff',
        '--auth-focus-ring': 'rgba(168, 85, 247, 0.2)',
        '--auth-primary-btn': 'linear-gradient(to right, #4F46E5, #9333EA, #EC4899)',
        '--auth-primary-shadow': 'rgba(147, 51, 234, 0.5)',
        '--auth-active-tab-bg': '#faf5ff',
        '--auth-active-tab-text': '#7e22ce',
        '--auth-active-tab-border': '#a855f7',
        '--auth-headline-size': '38px',
        '--auth-headline-mb': '12px',
        '--auth-desc-size': '15px',
        '--auth-desc-mb': '16px',
        '--auth-features-gap': '12px',
        '--auth-feature-item-gap': '16px',
        '--auth-feature-item-padding': '16px',
        '--auth-icon-size': '40px',
        '--auth-icon-radius': '12px',
        '--auth-svg-size': '20px',
        '--auth-h3-size': '15px',
        '--auth-h3-mb': '4px',
        '--auth-p-size': '13px',
        '--auth-p-lh': '1.4',
      };
    }
  };
  const themeVars = getThemeVars();"""

if old_theme_vars in content:
    content = content.replace(old_theme_vars, new_theme_vars)
    with open(path, 'w', encoding='utf-8') as f:
        f.write(content)
    print("Successfully replaced theme variables.")
else:
    print("Could not find the exact old_theme_vars string.")
