-- Supabase Rollback ("Down") Migration for 20260819010000_drop_legacy_mock_interview_tables.sql
-- Recreates legacy mock interview tables in parent-to-child order using exact schemas from migration history.

-- 1. Parent Table: mock_interviews (Source: beforeMigrate.sql / commit 09c75157)
CREATE TABLE IF NOT EXISTS mock_interviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    company VARCHAR(255),
    conversational_style VARCHAR(255),
    current_question_index INTEGER,
    current_state_json TEXT,
    experience_level VARCHAR(255),
    role VARCHAR(255),
    status VARCHAR(255),
    topic VARCHAR(255),
    transcript TEXT,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    completed_at TIMESTAMP WITHOUT TIME ZONE
);

-- 2. Child Table: interview_questions (Source: beforeMigrate.sql / commit 09c75157)
CREATE TABLE IF NOT EXISTS interview_questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mock_interview_id BIGINT NOT NULL REFERENCES mock_interviews(id) ON DELETE CASCADE,
    score INTEGER,
    thinking_time_seconds DOUBLE PRECISION,
    time_taken_seconds DOUBLE PRECISION,
    ai_feedback TEXT,
    answer_text TEXT,
    code_text TEXT,
    compiler_output TEXT,
    emotion_analysis_json TEXT,
    language VARCHAR(255),
    question_text TEXT
);

-- 3. Child Table: interview_feedback (Source: beforeMigrate.sql / commit 09c75157)
CREATE TABLE IF NOT EXISTS interview_feedback (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mock_interview_id BIGINT NOT NULL UNIQUE REFERENCES mock_interviews(id) ON DELETE CASCADE,
    behavioral_score INTEGER,
    coding_score INTEGER,
    communication_score INTEGER,
    company_readiness INTEGER,
    confidence_score INTEGER,
    hiring_probability INTEGER,
    interview_confidence INTEGER,
    problem_solving_score INTEGER,
    role_readiness INTEGER,
    technical_score INTEGER,
    total_score INTEGER,
    candidate_summary TEXT,
    communication_comment TEXT,
    competencies_json TEXT,
    culture_fit_comment TEXT,
    expected_salary VARCHAR(255),
    final_assessment TEXT,
    final_recommendation VARCHAR(255),
    leadership_comment TEXT,
    problem_solving_comment TEXT,
    recruiter_notes TEXT,
    recruiter_verdict VARCHAR(255),
    risk_assessment TEXT,
    team_fit_comment TEXT,
    technical_ability_comment TEXT
);

-- 4. Child Table: ai_observability_logs (Source: V13__add_mock_interview_observability_and_snapshots.sql)
CREATE TABLE IF NOT EXISTS ai_observability_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mock_interview_id BIGINT REFERENCES mock_interviews(id) ON DELETE SET NULL,
    task_type VARCHAR(255),
    prompt_version VARCHAR(255),
    model_version VARCHAR(255),
    provider_name VARCHAR(255),
    temperature DOUBLE PRECISION,
    top_p DOUBLE PRECISION,
    max_tokens INTEGER,
    latency_ms BIGINT,
    prompt_tokens INTEGER,
    completion_tokens INTEGER,
    total_tokens INTEGER,
    retry_count INTEGER,
    cost_estimate DOUBLE PRECISION,
    validation_status VARCHAR(255),
    validation_errors TEXT,
    success BOOLEAN,
    created_at TIMESTAMP WITHOUT TIME ZONE
);

-- 5. Child Table: mock_interview_snapshots (Source: V13__add_mock_interview_observability_and_snapshots.sql)
CREATE TABLE IF NOT EXISTS mock_interview_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mock_interview_id BIGINT NOT NULL REFERENCES mock_interviews(id) ON DELETE CASCADE,
    turn_index INTEGER,
    question_text TEXT,
    answer_text TEXT,
    evaluation_json TEXT,
    difficulty VARCHAR(255),
    knowledge_graph_snapshot_json TEXT,
    prompt_version VARCHAR(255),
    model_version VARCHAR(255),
    context_summary TEXT,
    created_at TIMESTAMP WITHOUT TIME ZONE
);

-- Performance Indexes (Source: V10 & V13)
CREATE INDEX IF NOT EXISTS idx_mock_interviews_user_id ON mock_interviews(user_id);
CREATE INDEX IF NOT EXISTS idx_interview_questions_mock_interview_id ON interview_questions(mock_interview_id);
CREATE INDEX IF NOT EXISTS idx_interview_feedback_mock_interview_id ON interview_feedback(mock_interview_id);
CREATE INDEX IF NOT EXISTS idx_ai_observability_logs_mock_interview_id ON ai_observability_logs(mock_interview_id);
CREATE INDEX IF NOT EXISTS idx_mock_interview_snapshots_mock_interview_id ON mock_interview_snapshots(mock_interview_id);
