apiVersion: v1

kind: Service

metadata:
  name: ai-placement-service

spec:
  selector:
    app: ai-placement-backend

  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

  type: LoadBalancer