-- Flyway Callback: beforeMigrate.sql
-- Dynamically creates mock 'auth' schemas on local/CI environments.
-- Also dynamically establishes the baseline public schema and seeds the Flyway schema history
-- with a version 9 baseline record if running on a clean database.

-- 1. Create auth schema and mock users table if it does not exist (e.g. standard PostgreSQL/local/CI)
CREATE SCHEMA IF NOT EXISTS auth;

CREATE TABLE IF NOT EXISTS auth.users (
    id UUID PRIMARY KEY,
    email VARCHAR(255) UNIQUE,
    raw_user_meta_data JSONB
);

-- 2. Build the baseline schema if this is a clean database (i.e. 'users' does not exist in 'public')
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT FROM pg_catalog.pg_tables 
        WHERE schemaname = 'public' 
        AND tablename = 'users'
    ) THEN
        RAISE NOTICE 'Clean database detected. Building baseline schema and history...';

        -- Create Flyway Schema History table manually to insert baseline version 9
        CREATE TABLE IF NOT EXISTS public.flyway_schema_history (
            installed_rank integer NOT NULL,
            version character varying(50),
            description character varying(200) NOT NULL,
            type character varying(20) NOT NULL,
            script character varying(1000) NOT NULL,
            checksum integer,
            installed_by character varying(100) NOT NULL,
            installed_on timestamp without time zone NOT NULL DEFAULT now(),
            execution_time integer NOT NULL,
            success boolean NOT NULL,
            CONSTRAINT flyway_schema_history_pk PRIMARY KEY (installed_rank)
        );
        CREATE INDEX IF NOT EXISTS flyway_schema_history_s_idx ON public.flyway_schema_history (success);

        -- Insert the baseline record at version 9
        INSERT INTO public.flyway_schema_history 
        (installed_rank, version, description, type, script, checksum, installed_by, execution_time, success)
        VALUES 
        (1, '9', '<< Flyway Baseline >>', 'BASELINE', '<< Flyway Baseline >>', NULL, CURRENT_USER, 0, TRUE)
        ON CONFLICT (installed_rank) DO NOTHING;

        CREATE TABLE admin_notifications (
            resolved boolean not null, 
            id bigint generated by default as identity, 
            timestamp timestamp(6) not null, 
            message TEXT not null, 
            type varchar(255) not null, 
            primary key (id)
        );

        CREATE TABLE admin_sessions (
            created_at timestamp(6) not null, 
            expires_at timestamp(6) not null, 
            id bigint generated by default as identity, 
            admin_email varchar(255) not null, 
            csrf_token varchar(255), 
            ip_address varchar(255), 
            token varchar(255) not null unique, 
            user_agent varchar(255), 
            primary key (id)
        );

        CREATE TABLE admin_users (
            failed_login_attempts integer not null, 
            created_at timestamp(6), 
            id bigint generated by default as identity, 
            lockout_until timestamp(6), 
            updated_at timestamp(6), 
            email varchar(255) not null unique, 
            password_hash varchar(255) not null, 
            primary key (id)
        );

        CREATE TABLE analytics_snapshots (
            snapshot_date date not null unique, 
            id bigint generated by default as identity, 
            metrics_json TEXT not null, 
            primary key (id)
        );

        CREATE TABLE api_usage_logs (
            completion_length integer, 
            completion_tokens integer, 
            estimated_cost float(53), 
            prompt_length integer, 
            prompt_tokens integer, 
            retry_count integer, 
            total_tokens integer, 
            id bigint generated by default as identity, 
            latency_ms bigint, 
            timestamp timestamp(6) not null, 
            ai_model varchar(255), 
            feature_used varchar(255), 
            provider varchar(255), 
            status varchar(255), 
            user_email varchar(255), 
            primary key (id)
        );

        CREATE TABLE ats_analysis (
            ats_score integer, 
            created_at timestamp(6), 
            id bigint generated by default as identity, 
            resume_id bigint unique, 
            user_id bigint, 
            best_role varchar(255), 
            extracted_text TEXT, 
            primary key (id)
        );

        CREATE TABLE ats_matched_keywords (
            ats_analysis_id bigint not null, 
            keyword varchar(255)
        );

        CREATE TABLE ats_missing_keywords (
            ats_analysis_id bigint not null, 
            keyword varchar(255)
        );

        CREATE TABLE ats_strengths (
            ats_analysis_id bigint not null, 
            strength TEXT
        );

        CREATE TABLE ats_suggestions (
            ats_analysis_id bigint not null, 
            suggestion TEXT
        );

        CREATE TABLE ats_weaknesses (
            ats_analysis_id bigint not null, 
            weakness TEXT
        );

        CREATE TABLE audit_logs (
            id bigint generated by default as identity, 
            timestamp timestamp(6) not null, 
            action varchar(255) not null, 
            admin_email varchar(255), 
            browser varchar(255), 
            ip_address varchar(255), 
            os varchar(255), 
            status varchar(255) not null, 
            target TEXT, 
            primary key (id)
        );

        CREATE TABLE candidate_claims (
            confidence float(53), 
            id bigint generated by default as identity, 
            user_id bigint not null, 
            claim_text TEXT, 
            evidence TEXT, 
            recruiter_risk varchar(255), 
            verification_status varchar(255), 
            primary key (id)
        );

        CREATE TABLE candidate_concepts (
            confidence float(53), 
            id bigint generated by default as identity, 
            user_id bigint not null, 
            concept_name varchar(255), 
            primary key (id)
        );

        CREATE TABLE candidate_contradictions (
            id bigint generated by default as identity, 
            user_id bigint not null, 
            contradiction_text TEXT, 
            related_questions TEXT, 
            severity varchar(255), 
            suggested_followup TEXT, 
            primary key (id)
        );

        CREATE TABLE candidate_followups (
            priority integer, 
            id bigint generated by default as identity, 
            user_id bigint not null, 
            question_text TEXT, 
            status varchar(255), 
            topic varchar(255), 
            primary key (id)
        );

        CREATE TABLE candidate_learning_progress (
            improvement float(53), 
            new_confidence float(53), 
            previous_confidence float(53), 
            regression float(53), 
            id bigint generated by default as identity, 
            interview_date timestamp(6), 
            user_id bigint not null, 
            skill varchar(255), 
            trend varchar(255), 
            primary key (id)
        );

        CREATE TABLE candidate_project_knowledge (
            confidence float(53), 
            id bigint generated by default as identity, 
            user_id bigint not null, 
            architecture TEXT, 
            caching TEXT, 
            database_tech TEXT, 
            deployment TEXT, 
            devops TEXT, 
            monitoring TEXT, 
            project_name varchar(255), 
            scaling TEXT, 
            security TEXT, 
            testing TEXT, 
            primary key (id)
        );

        CREATE TABLE candidate_skill_confidence (
            average_score float(53), 
            claimed boolean, 
            confidence float(53), 
            correct_answers integer, 
            incorrect_answers integer, 
            question_count integer, 
            verified boolean, 
            id bigint generated by default as identity, 
            last_verified timestamp(6), 
            user_id bigint not null, 
            skill varchar(255), 
            trend varchar(255), 
            primary key (id)
        );

        CREATE TABLE candidate_verified_resume (
            confidence float(53), 
            id bigint generated by default as identity, 
            user_id bigint not null, 
            claim TEXT, 
            risk varchar(255), 
            status varchar(255), 
            primary key (id)
        );

        CREATE TABLE candidate_voice_profiles (
            avg_response_latency float(53), 
            avg_speaking_speed float(53), 
            clarity_score float(53), 
            emotional_stability float(53), 
            filler_word_frequency float(53), 
            interview_maturity float(53), 
            overall_behavioral_score float(53), 
            id bigint generated by default as identity, 
            last_updated timestamp(6), 
            user_id bigint not null unique, 
            primary key (id)
        );

        CREATE TABLE chat_conversations (
            estimated_cost float(53) not null, 
            estimated_token_usage integer not null, 
            is_archived boolean not null, 
            is_pinned boolean not null, 
            message_count integer not null, 
            created_at timestamp(6), 
            id bigint generated by default as identity, 
            updated_at timestamp(6), 
            user_id bigint not null, 
            summary TEXT, 
            title varchar(255) not null, 
            primary key (id)
        );

        CREATE TABLE chat_memories (
            importance_score integer not null, 
            is_pinned boolean not null, 
            created_at timestamp(6), 
            id bigint generated by default as identity, 
            updated_at timestamp(6), 
            user_id bigint not null, 
            content TEXT not null, 
            memory_type varchar(255) not null, 
            primary key (id)
        );

        CREATE TABLE chat_messages (
            completion_tokens integer not null, 
            is_edited boolean not null, 
            is_pinned boolean not null, 
            prompt_tokens integer not null, 
            conversation_id bigint not null, 
            created_at timestamp(6), 
            id bigint generated by default as identity, 
            latency_ms bigint not null, 
            parent_message_id bigint, 
            attachments_json TEXT, 
            content TEXT not null, 
            finish_reason varchar(255), 
            model_used varchar(255) not null, 
            sender varchar(255) not null, 
            primary key (id)
        );

        CREATE TABLE coding_complexity (
            complexity_score float(53), 
            has_infinite_loop_risk boolean not null, 
            has_memory_leak boolean not null, 
            has_recursion_issue boolean not null, 
            is_brute_force boolean not null, 
            is_optimal boolean not null, 
            coding_submission_id bigint not null unique, 
            id bigint generated by default as identity, 
            analysis TEXT, 
            detected_patterns TEXT, 
            estimated_space_complexity varchar(255), 
            estimated_time_complexity varchar(255), 
            expected_space_complexity varchar(255), 
            expected_time_complexity varchar(255), 
            optimization_suggestions TEXT, 
            primary key (id)
        );

        CREATE TABLE coding_evaluations (
            best_practices float(53), 
            confidence float(53), 
            correctness float(53), 
            error_handling float(53), 
            logic float(53), 
            maintainability float(53), 
            memory_usage float(53), 
            modularity float(53), 
            naming float(53), 
            overall_score float(53), 
            performance float(53), 
            readability float(53), 
            scalability float(53), 
            security float(53), 
            structure float(53), 
            coding_submission_id bigint not null unique, 
            id bigint generated by default as identity, 
            code_smells TEXT, 
            improvement_suggestions TEXT, 
            review_text TEXT, 
            security_issues TEXT, 
            strengths TEXT, 
            weaknesses TEXT, 
            primary key (id)
        );

        CREATE TABLE coding_executions (
            passed boolean not null, 
            test_case_ordinal integer not null, 
            coding_submission_id bigint not null, 
            coding_test_case_id bigint, 
            id bigint generated by default as identity, 
            memory_mb bigint, 
            runtime_ms bigint, 
            actual_output TEXT, 
            error_message TEXT, 
            execution_type varchar(255), 
            expected_output TEXT, 
            input TEXT, 
            verdict varchar(255), 
            primary key (id)
        );

        CREATE TABLE coding_language_profiles (
            accepted_count integer, 
            algorithm_score float(53), 
            avg_execution_time_ms float(53), 
            avg_pass_rate float(53), 
            avg_score float(53), 
            best_score float(53), 
            compile_error_count integer, 
            confidence float(53), 
            data_structure_score float(53), 
            sql_score float(53), 
            submission_count integer, 
            time_limit_count integer, 
            wrong_answer_count integer, 
            id bigint generated by default as identity, 
            last_updated timestamp(6), 
            user_id bigint not null, 
            language varchar(255) not null, 
            primary key (id), 
            unique (user_id, language)
        );

        CREATE TABLE coding_problems (
            created_at timestamp(6), 
            id bigint generated by default as identity, 
            interview_question_id bigint unique, 
            mock_interview_id bigint not null, 
            constraints TEXT, 
            difficulty varchar(255), 
            examples TEXT, 
            hints TEXT, 
            problem_statement TEXT not null, 
            solution_approach TEXT, 
            space_complexity_target varchar(255), 
            tags TEXT, 
            target_languages TEXT, 
            time_complexity_target varchar(255), 
            title varchar(255) not null, 
            primary key (id)
        );

        CREATE TABLE coding_replays (
            character_count integer not null, 
            line_count integer not null, 
            snapshot_index integer not null, 
            coding_submission_id bigint not null, 
            id bigint generated by default as identity, 
            snapshot_timestamp timestamp(6), 
            event_type varchar(255), 
            snapshot_code TEXT, 
            primary key (id)
        );

        CREATE TABLE coding_submissions (
            attempt_number integer not null, 
            pass_rate integer, 
            passed_tests integer, 
            plagiarism_flagged boolean not null, 
            plagiarism_score float(53), 
            total_tests integer, 
            coding_problem_id bigint, 
            execution_time_ms bigint, 
            id bigint generated by default as identity, 
            interview_question_id bigint not null, 
            memory_used_mb bigint, 
            submitted_at timestamp(6), 
            code TEXT not null, 
            compile_output TEXT, 
            language varchar(255), 
            status varchar(255), 
            primary key (id)
        );

        CREATE TABLE coding_test_cases (
            boundary boolean not null, 
            hidden boolean not null, 
            memory_limit_mb integer not null, 
            ordinal integer not null, 
            performance boolean not null, 
            randomized boolean not null, 
            timeout_ms integer not null, 
            coding_problem_id bigint not null, 
            id bigint generated by default as identity, 
            description TEXT, 
            expected_output TEXT, 
            input TEXT, 
            primary key (id)
        );

        CREATE TABLE company_profiles (
            created_at timestamp(6), 
            id bigint generated by default as identity, 
            recruiter_id bigint not null unique, 
            updated_at timestamp(6), 
            benefits TEXT, 
            careers_website varchar(255), 
            company_culture TEXT, 
            company_name varchar(255), 
            company_size varchar(255), 
            description TEXT, 
            headquarters varchar(255), 
            hiring_manager_details varchar(255), 
            hiring_preferences TEXT, 
            industry varchar(255), 
            linkedin_url varchar(255), 
            logo_url varchar(255), 
            office_locations TEXT, 
            primary key (id)
        );

        CREATE TABLE company_requirements (
            created_at timestamp(6), 
            id bigint generated by default as identity, 
            updated_at timestamp(6), 
            company_name varchar(255) not null unique, 
            required_skills TEXT, 
            primary key (id)
        );

        CREATE TABLE credit_usage_logs (
            credits_used integer not null, 
            id bigint generated by default as identity, 
            timestamp timestamp(6) not null, 
            user_id bigint not null, 
            action_type varchar(255) not null, 
            primary key (id)
        );

        CREATE TABLE delete_account_verification (
            attempts integer not null, 
            resend_count integer not null, 
            created_at timestamp(6) not null, 
            expires_at timestamp(6) not null, 
            id bigint generated by default as identity, 
            last_resend_at timestamp(6), 
            user_id bigint not null, 
            email varchar(255) not null, 
            otp_hash varchar(255) not null, 
            primary key (id)
        );

        CREATE TABLE email_verification_otp (
            verified boolean not null, 
            created_at timestamp(6) not null, 
            expires_at timestamp(6) not null, 
            id bigint generated by default as identity, 
            email varchar(255) not null unique, 
            otp varchar(255) not null, 
            primary key (id)
        );

        CREATE TABLE evaluation_audits (
            evaluation_id bigint not null, 
            id bigint generated by default as identity, 
            timestamp timestamp(6), 
            action varchar(255), 
            actor varchar(255), 
            details TEXT, 
            primary key (id)
        );

        CREATE TABLE evaluation_versions (
            score_snapshot float(53), 
            version integer, 
            created_at timestamp(6), 
            evaluation_id bigint not null, 
            id bigint generated by default as identity, 
            primary key (id)
        );

        CREATE TABLE events (
            created_at timestamp(6), 
            id bigint generated by default as identity, 
            user_id bigint not null, 
            color varchar(255), 
            company varchar(255) not null, 
            event_date varchar(255) not null, 
            event_time varchar(255) not null, 
            type varchar(255) not null, 
            primary key (id)
        );

        CREATE TABLE feedback_body_language (
            feedback_id bigint not null, 
            tip varchar(255)
        );

        CREATE TABLE feedback_improvements (
            feedback_id bigint not null, 
            improvement varchar(255)
        );

        CREATE TABLE feedback_missed_topics (
            feedback_id bigint not null, 
            topic varchar(255)
        );

        CREATE TABLE feedback_plans (
            feedback_id bigint not null, 
            plan varchar(255)
        );

        CREATE TABLE feedback_resources (
            feedback_id bigint not null, 
            resource varchar(255)
        );

        CREATE TABLE feedback_strengths (
            feedback_id bigint not null, 
            strength varchar(255)
        );

        CREATE TABLE interview_architecture_metrics (
            decoupling float(53), 
            patterns_understanding float(53), 
            reliability float(53), 
            resilience float(53), 
            scalability float(53), 
            evaluation_id bigint not null, 
            id bigint generated by default as identity, 
            primary key (id)
        );

        CREATE TABLE interview_behavior_metrics (
            accountability float(53), 
            action_score float(53), 
            conflict_resolution float(53), 
            growth_mindset float(53), 
            initiative float(53), 
            leadership float(53), 
            ownership float(53), 
            result_score float(53), 
            situation_score float(53), 
            task_score float(53), 
            evaluation_id bigint not null, 
            id bigint generated by default as identity, 
            primary key (id)
        );

        CREATE TABLE interview_communication_metrics (
            clarity float(53), 
            conciseness float(53), 
            confidence float(53), 
            examples_count integer, 
            organization float(53), 
            professionalism float(53), 
            speaking_flow float(53), 
            structure float(53), 
            vocabulary_usage float(53), 
            evaluation_id bigint not null, 
            id bigint generated by default as identity, 
            primary key (id)
        );

        CREATE TABLE interview_competency_scores (
            confidence float(53), 
            score float(53), 
            evaluation_id bigint not null, 
            id bigint generated by default as identity, 
            competency varchar(255), 
            trend varchar(255), 
            primary key (id)
        );

        CREATE TABLE interview_evaluations (
            confidence float(53), 
            overall_score float(53), 
            version integer, 
            created_at timestamp(6), 
            id bigint generated by default as identity, 
            mock_interview_id bigint not null, 
            evaluator_name varchar(255), 
            primary key (id)
        );

        CREATE TABLE interview_evidence (
            evaluation_id bigint not null, 
            id bigint generated by default as identity, 
            competency varchar(255), 
            evidence_text TEXT, 
            source_answer TEXT, 
            source_question TEXT, 
            primary key (id)
        );

        CREATE TABLE interview_feedback (
            behavioral_score integer, 
            coding_score integer, 
            communication_score integer, 
            company_readiness integer, 
            confidence_score integer, 
            hiring_probability integer, 
            interview_confidence integer, 
            problem_solving_score integer, 
            role_readiness integer, 
            technical_score integer, 
            total_score integer, 
            id bigint generated by default as identity, 
            mock_interview_id bigint not null unique, 
            candidate_summary TEXT, 
            communication_comment TEXT, 
            competencies_json TEXT, 
            culture_fit_comment TEXT, 
            expected_salary varchar(255), 
            final_assessment TEXT, 
            final_recommendation varchar(255), 
            leadership_comment TEXT, 
            problem_solving_comment TEXT, 
            recruiter_notes TEXT, 
            recruiter_verdict varchar(255), 
            risk_assessment TEXT, 
            team_fit_comment TEXT, 
            technical_ability_comment TEXT, 
            primary key (id)
        );

        CREATE TABLE interview_hiring_decisions (
            interview_confidence float(53), 
            evaluation_id bigint not null, 
            id bigint generated by default as identity, 
            decision varchar(255), 
            evidence TEXT, 
            reasons TEXT, 
            recommended_level varchar(255), 
            recommended_team varchar(255), 
            risks TEXT, 
            strengths TEXT, 
            weaknesses TEXT, 
            primary key (id)
        );

        CREATE TABLE interview_improvements (
            evaluation_id bigint not null, 
            id bigint generated by default as identity, 
            improvement_area TEXT, 
            suggestion TEXT, 
            primary key (id)
        );

        CREATE TABLE interview_interruption_logs (
            id bigint generated by default as identity, 
            interview_question_id bigint, 
            mock_interview_id bigint not null, 
            timestamp timestamp(6), 
            action_taken varchar(255), 
            ai_response_text TEXT, 
            classification varchar(255) not null, 
            transcription TEXT, 
            primary key (id)
        );

        CREATE TABLE interview_leadership_metrics (
            collaboration float(53), 
            decision_making float(53), 
            influence float(53), 
            mentoring float(53), 
            ownership float(53), 
            evaluation_id bigint not null, 
            id bigint generated by default as identity, 
            primary key (id)
        );

        CREATE TABLE interview_questions (
            score integer, 
            thinking_time_seconds float(53), 
            time_taken_seconds float(53), 
            id bigint generated by default as identity, 
            mock_interview_id bigint not null, 
            ai_feedback TEXT, 
            answer_text TEXT, 
            code_text TEXT, 
            compiler_output TEXT, 
            emotion_analysis_json TEXT, 
            language varchar(255), 
            question_text TEXT, 
            primary key (id)
        );

        CREATE TABLE interview_reasoning (
            evaluation_id bigint not null, 
            id bigint generated by default as identity, 
            competency varchar(255), 
            reasoning_text TEXT, 
            primary key (id)
        );

        CREATE TABLE interview_recommendations (
            evaluation_id bigint not null, 
            id bigint generated by default as identity, 
            recommendation_text TEXT, 
            type varchar(255), 
            primary key (id)
        );

        CREATE TABLE interview_records (
            score integer, 
            id bigint generated by default as identity, 
            interview_date timestamp(6), 
            user_id bigint not null, 
            role varchar(255), 
            primary key (id)
        );

        CREATE TABLE interview_schedules (
            duration integer, 
            is_completed boolean not null, 
            reminder_sent boolean, 
            application_id bigint, 
            created_at timestamp(6), 
            id bigint generated by default as identity, 
            recruiter_id bigint not null, 
            scheduled_date timestamp(6) not null, 
            student_id bigint not null, 
            updated_at timestamp(6), 
            interviewer_details varchar(255), 
            interviewer_email varchar(255), 
            interviewer_name varchar(255), 
            meeting_link varchar(255), 
            mode varchar(255), 
            round varchar(255), 
            status varchar(255), 
            primary key (id)
        );

        CREATE TABLE interview_skill_gaps (
            current_level float(53), 
            expected_level float(53), 
            gap float(53), 
            priority integer, 
            evaluation_id bigint not null, 
            id bigint generated by default as identity, 
            estimated_improvement_time varchar(255), 
            skill varchar(255), 
            training_suggestions TEXT, 
            primary key (id)
        );

        CREATE TABLE interview_technical_metrics (
            architecture float(53), 
            best_practices float(53), 
            completeness float(53), 
            complexity float(53), 
            correctness float(53), 
            depth float(53), 
            optimization float(53), 
            performance float(53), 
            scalability float(53), 
            security float(53), 
            trade_offs float(53), 
            evaluation_id bigint not null, 
            id bigint generated by default as identity, 
            primary key (id)
        );

        CREATE TABLE job_applications (
            ats_score integer, 
            coding_score integer, 
            interview_score integer, 
            jd_match_score integer, 
            created_at timestamp(6), 
            id bigint generated by default as identity, 
            job_id bigint not null, 
            student_id bigint not null, 
            updated_at timestamp(6), 
            status varchar(255) not null, 
            primary key (id)
        );

        CREATE TABLE jobs (
            deadline date, 
            is_active boolean not null, 
            min_ats_score integer, 
            min_cgpa float(53), 
            company_profile_id bigint, 
            created_at timestamp(6), 
            id bigint generated by default as identity, 
            recruiter_id bigint not null, 
            salary_max bigint, 
            salary_min bigint, 
            updated_at timestamp(6), 
            company varchar(255) not null, 
            departments TEXT, 
            description TEXT, 
            employment_type varchar(255), 
            experience_level varchar(255), 
            location varchar(255), 
            required_skills TEXT, 
            status varchar(255), 
            title varchar(255) not null, 
            work_mode varchar(255), 
            primary key (id)
        );

        CREATE TABLE knowledge_graph_edges (
            weight float(53), 
            id bigint generated by default as identity, 
            source_node_id bigint, 
            target_node_id bigint, 
            user_id bigint not null, 
            relationship varchar(255), 
            primary key (id)
        );

        CREATE TABLE knowledge_graph_nodes (
            id bigint generated by default as identity, 
            user_id bigint not null, 
            name varchar(255), 
            type varchar(255), 
            primary key (id)
        );

        CREATE TABLE memory_events (
            id bigint generated by default as identity, 
            interview_id bigint, 
            timestamp timestamp(6), 
            user_id bigint not null, 
            details TEXT, 
            event_type varchar(255), 
            primary key (id)
        );

        CREATE TABLE mock_interviews (
            current_question_index integer, 
            completed_at timestamp(6), 
            created_at timestamp(6), 
            id bigint generated by default as identity, 
            user_id bigint not null, 
            company varchar(255), 
            conversational_style varchar(255), 
            current_state_json TEXT, 
            experience_level varchar(255), 
            role varchar(255), 
            status varchar(255), 
            topic varchar(255), 
            transcript TEXT, 
            primary key (id)
        );

        CREATE TABLE password_reset_otps (
            verified boolean not null, 
            created_at timestamp(6) not null, 
            expires_at timestamp(6) not null, 
            id bigint generated by default as identity, 
            email varchar(255) not null, 
            otp varchar(255) not null, 
            primary key (id)
        );

        CREATE TABLE prompt_definitions (
            created_at timestamp(6), 
            id bigint generated by default as identity, 
            description varchar(255), 
            prompt_key varchar(255) not null unique, 
            primary key (id)
        );

        CREATE TABLE prompt_versions (
            is_active boolean not null, 
            version_number integer not null, 
            created_at timestamp(6), 
            id bigint generated by default as identity, 
            prompt_definition_id bigint not null, 
            prompt_text TEXT not null, 
            primary key (id), 
            unique (prompt_definition_id, version_number)
        );

        CREATE TABLE push_subscriptions (
            id bigint generated by default as identity, 
            user_id bigint not null, 
            endpoint varchar(1000) not null, 
            auth varchar(255) not null, 
            p256dh varchar(255) not null, 
            primary key (id)
        );

        CREATE TABLE recruiter_notes (
            is_private boolean, 
            rating integer, 
            application_id bigint, 
            created_at timestamp(6), 
            id bigint generated by default as identity, 
            recruiter_id bigint not null, 
            student_id bigint not null, 
            updated_at timestamp(6), 
            content TEXT not null, 
            tags TEXT, 
            primary key (id)
        );

        CREATE TABLE resume_builders (
            id bigint generated by default as identity, 
            user_id bigint, 
            certifications TEXT, 
            education TEXT, 
            email varchar(255), 
            experience TEXT, 
            full_name varchar(255), 
            github varchar(255), 
            linkedin varchar(255), 
            phone varchar(255), 
            projects TEXT, 
            skills TEXT, 
            summary TEXT, 
            template_name varchar(255), 
            title varchar(255), 
            primary key (id)
        );

        CREATE TABLE resumes (
            ats_score integer, 
            created_at timestamp(6), 
            id bigint generated by default as identity, 
            user_id bigint, 
            analyzed_role varchar(255), 
            extracted_text TEXT, 
            file_name varchar(255), 
            file_path varchar(255), 
            missing_keywords varchar(255), 
            strengths varchar(255), 
            weaknesses varchar(255), 
            primary key (id)
        );

        CREATE TABLE signup_verification (
            attempts integer not null, 
            graduation_year integer, 
            resend_count integer not null, 
            semester integer, 
            created_at timestamp(6) not null, 
            expires_at timestamp(6) not null, 
            id bigint generated by default as identity, 
            last_resend_at timestamp(6), 
            branch varchar(255), 
            college varchar(255), 
            company_name varchar(255), 
            email varchar(255) not null unique, 
            full_name varchar(255) not null, 
            otp_hash varchar(255) not null, 
            password_hash varchar(255) not null, 
            phone varchar(255), 
            preferred_role varchar(255), 
            role varchar(255), 
            skills TEXT, 
            primary key (id)
        );

        CREATE TABLE support_tickets (
            created_at timestamp(6), 
            id bigint generated by default as identity, 
            user_id bigint not null, 
            message TEXT not null, 
            status varchar(255) not null, 
            subject varchar(255) not null, 
            primary key (id)
        );

        CREATE TABLE system_design_diagram_replays (
            component_count integer not null, 
            connection_count integer not null, 
            snapshot_index integer not null, 
            id bigint generated by default as identity, 
            snapshot_timestamp timestamp(6), 
            system_design_diagram_id bigint not null, 
            components_json TEXT, 
            connections_json TEXT, 
            primary key (id)
        );

        CREATE TABLE system_design_diagrams (
            id bigint generated by default as identity, 
            interview_question_id bigint not null unique, 
            last_saved_at timestamp(6), 
            mock_interview_id bigint not null, 
            candidate_notes TEXT, 
            components_json TEXT, 
            connections_json TEXT, 
            primary key (id)
        );

        CREATE TABLE system_design_evaluations (
            api_design_score float(53), 
            caching_score float(53), 
            confidence float(53), 
            database_design_score float(53), 
            disaster_recovery_score float(53), 
            distributed_systems_score float(53), 
            load_balancing_score float(53), 
            message_queues_score float(53), 
            metric_architecture_score float(53), 
            metric_decision_making_score float(53), 
            metric_performance_score float(53), 
            metric_reliability_score float(53), 
            metric_scalability_score float(53), 
            metric_security_score float(53), 
            metric_trade_off_score float(53), 
            microservices_score float(53), 
            monitoring_score float(53), 
            overall_score float(53), 
            requirements_score float(53), 
            scalability_score float(53), 
            security_score float(53), 
            trade_offs_score float(53), 
            id bigint generated by default as identity, 
            interview_question_id bigint unique, 
            system_design_diagram_id bigint not null unique, 
            feedback_text TEXT, 
            metric_architecture_evidence TEXT, 
            metric_architecture_improvement TEXT, 
            metric_architecture_reasoning TEXT, 
            metric_decision_making_evidence TEXT, 
            metric_decision_making_improvement TEXT, 
            metric_decision_making_reasoning TEXT, 
            metric_performance_evidence TEXT, 
            metric_performance_improvement TEXT, 
            metric_performance_reasoning TEXT, 
            metric_reliability_evidence TEXT, 
            metric_reliability_improvement TEXT, 
            metric_reliability_reasoning TEXT, 
            metric_scalability_evidence TEXT, 
            metric_scalability_improvement TEXT, 
            metric_scalability_reasoning TEXT, 
            metric_security_evidence TEXT, 
            metric_security_improvement TEXT, 
            metric_security_reasoning TEXT, 
            metric_trade_off_evidence TEXT, 
            metric_trade_off_improvement TEXT, 
            metric_trade_off_reasoning TEXT, 
            primary key (id)
        );

        CREATE TABLE system_design_scenarios (
            created_at timestamp(6), 
            id bigint generated by default as identity, 
            interview_question_id bigint not null unique, 
            description TEXT not null, 
            expected_components TEXT, 
            hints TEXT, 
            sla_requirements TEXT, 
            target_scale varchar(255), 
            title varchar(255) not null, 
            trade_off_instructions TEXT, 
            primary key (id)
        );

        CREATE TABLE system_metrics (
            cpu_usage float(53), 
            disk_usage float(53), 
            error_rate float(53), 
            ram_usage float(53), 
            api_latency bigint, 
            average_response_time bigint, 
            id bigint generated by default as identity, 
            timestamp timestamp(6) not null, 
            primary key (id)
        );

        CREATE TABLE user_activity_logs (
            activity_date date not null, 
            duration_minutes integer not null, 
            id bigint generated by default as identity, 
            user_id bigint not null, 
            primary key (id)
        );

        CREATE TABLE user_stats (
            activity_streak_days integer not null, 
            questions_easy integer not null, 
            questions_hard integer not null, 
            questions_medium integer not null, 
            resume_verified boolean not null, 
            id bigint generated by default as identity, 
            user_id bigint unique, 
            primary key (id)
        );

        CREATE TABLE users (
            ats_score integer not null, 
            auto_save boolean, 
            coding_score integer not null, 
            communication_score integer not null, 
            credits_remaining integer not null, 
            credits_used integer not null, 
            delete_failed_attempts integer not null, 
            email_notifications boolean, 
            email_verified boolean, 
            graduation_year integer, 
            interview_score integer not null, 
            payment_completed boolean, 
            plan_selected boolean, 
            profile_completed boolean, 
            profile_visible boolean, 
            push_notifications boolean, 
            readiness_score integer not null, 
            two_factor_enabled boolean, 
            welcome_email_sent boolean, 
            created_at timestamp(6), 
            delete_lock_expires_at timestamp(6), 
            id bigint generated by default as identity, 
            last_active timestamp(6), 
            updated_at timestamp(6), 
            verified_at timestamp(6), 
            supabase_uuid uuid unique, 
            payment_status varchar(20), 
            plan varchar(20), 
            account_status varchar(255), 
            aptitude_data TEXT, 
            auth_provider varchar(255), 
            branch varchar(255), 
            college_name varchar(255), 
            company_name varchar(255), 
            company_size varchar(255), 
            company_website varchar(255), 
            date_of_birth varchar(255), 
            designation varchar(255), 
            email varchar(255) not null unique, 
            full_name varchar(255) not null, 
            github_url varchar(255), 
            language varchar(255), 
            leetcode_url varchar(255), 
            linkedin_url varchar(255), 
            password varchar(255) not null, 
            phone varchar(255), 
            profile_image varchar(255), 
            role varchar(255), 
            skills TEXT, 
            primary key (id)
        );

        CREATE TABLE voice_audio_records (
            created_at timestamp(6), 
            duration_ms bigint, 
            file_size bigint, 
            id bigint generated by default as identity, 
            interview_question_id bigint not null unique, 
            audio_url varchar(255) not null, 
            mime_type varchar(255), 
            transcription TEXT, 
            primary key (id)
        );

        CREATE TABLE voice_timeline_segments (
            confidence_score float(53), 
            engagement_score float(53), 
            enthusiasm_score float(53), 
            filler_words_count integer, 
            nervousness_score float(53), 
            speech_rate_wpm float(53), 
            stress_score float(53), 
            answer_end timestamp(6), 
            answer_start timestamp(6), 
            created_at timestamp(6), 
            id bigint generated by default as identity, 
            interview_question_id bigint not null unique, 
            mock_interview_id bigint not null, 
            question_timestamp timestamp(6), 
            silence_duration_ms bigint, 
            speaking_duration_ms bigint, 
            thinking_time_ms bigint, 
            primary key (id)
        );

        CREATE INDEX idx_admin_notification_timestamp on admin_notifications (timestamp);
        CREATE INDEX idx_admin_session_email on admin_sessions (admin_email);
        CREATE INDEX idx_api_usage_timestamp on api_usage_logs (timestamp);
        CREATE INDEX idx_api_usage_user_email on api_usage_logs (user_email);
        CREATE INDEX idx_ats_analysis_user_id on ats_analysis (user_id);
        CREATE INDEX idx_ats_analysis_resume_id on ats_analysis (resume_id);
        CREATE INDEX idx_audit_log_timestamp on audit_logs (timestamp);
        CREATE INDEX idx_audit_log_admin_email on audit_logs (admin_email);
        CREATE INDEX idx_credit_usage_timestamp on credit_usage_logs (timestamp);
        CREATE INDEX idx_credit_usage_user_id on credit_usage_logs (user_id);
        CREATE INDEX idx_resume_user_id on resumes (user_id);
        CREATE INDEX idx_system_metric_timestamp on system_metrics (timestamp);
        CREATE INDEX idx_user_activity_date on user_activity_logs (user_id, activity_date);
        CREATE INDEX idx_user_role on users (role);
        CREATE INDEX idx_user_college_branch on users (college_name, branch);
        CREATE INDEX idx_user_created_active on users (created_at, last_active);
        CREATE INDEX idx_user_readiness_score on users (readiness_score);

        ALTER TABLE ats_analysis add constraint FKqh3enxqf7kf8nwgegtyhv97n4 foreign key (resume_id) references resumes;
        ALTER TABLE ats_analysis add constraint FKbn74bjrnhw67gb8obnhggdjih foreign key (user_id) references users;
        ALTER TABLE ats_matched_keywords add constraint FKthrtjwaqxnnf2prhd53f6nrnu foreign key (ats_analysis_id) references ats_analysis;
        ALTER TABLE ats_missing_keywords add constraint FKqasbin52u3pk24vuujqyaqba foreign key (ats_analysis_id) references ats_analysis;
        ALTER TABLE ats_strengths add constraint FKe00ga591brq66sm6d59dxa9vo foreign key (ats_analysis_id) references ats_analysis;
        ALTER TABLE ats_suggestions add constraint FKccgqpot6q129n4x7487pm6sw4 foreign key (ats_analysis_id) references ats_analysis;
        ALTER TABLE ats_weaknesses add constraint FKjmtp0js3o8kw78uqh7b5vtxmu foreign key (ats_analysis_id) references ats_analysis;
        ALTER TABLE candidate_claims add constraint FKc3yiu73pfshry50ri9vrxoy6r foreign key (user_id) references users;
        ALTER TABLE candidate_concepts add constraint FKfgym5s7mj5w7kj0xiy32vsa3s foreign key (user_id) references users;
        ALTER TABLE candidate_contradictions add constraint FKrgij3yk0ionswrufychepkwb4 foreign key (user_id) references users;
        ALTER TABLE candidate_followups add constraint FKf8v26b3ednpkmgt4xbp62fp4d foreign key (user_id) references users;
        ALTER TABLE candidate_learning_progress add constraint FKl7qgneugobsonjrdmhj43w3hb foreign key (user_id) references users;
        ALTER TABLE candidate_project_knowledge add constraint FKgg5nlhvt8hsp1pu5m28ldjyic foreign key (user_id) references users;
        ALTER TABLE candidate_skill_confidence add constraint FK6gbdmufikvmxqlgba1b908qis foreign key (user_id) references users;
        ALTER TABLE candidate_verified_resume add constraint FKsslfhh13uufw007cu93gvekf9 foreign key (user_id) references users;
        ALTER TABLE candidate_voice_profiles add constraint FK8876sjl6s3gom2ts2t7o7xwwo foreign key (user_id) references users;
        ALTER TABLE chat_conversations add constraint FK40okueacd48n616c3r1nvjwpr foreign key (user_id) references users;
        ALTER TABLE chat_memories add constraint FK1o2fca0b82lygf82ty87nx9uh foreign key (user_id) references users;
        ALTER TABLE chat_messages add constraint FKqgkanrr90j46564w4ww63jcna foreign key (conversation_id) references chat_conversations;
        ALTER TABLE chat_messages add constraint FK6wmkv55kk8d7rlwdef7op58se foreign key (parent_message_id) references chat_messages;
        ALTER TABLE coding_complexity add constraint FK6al0wfp8km69jnpjeca8s2gqg foreign key (coding_submission_id) references coding_submissions;
        ALTER TABLE coding_evaluations add constraint FK4t05v1xk1vygxfkpf84pjkn7i foreign key (coding_submission_id) references coding_submissions;
        ALTER TABLE coding_executions add constraint FKcvl29ml7iymb7bln7qo34hk7s foreign key (coding_submission_id) references coding_submissions;
        ALTER TABLE coding_executions add constraint FKsrwdhlbjyp6mt42lrclqryflj foreign key (coding_test_case_id) references coding_test_cases;
        ALTER TABLE coding_language_profiles add constraint FKfhjm1mk71k495wttnvrjy5kug foreign key (user_id) references users;
        ALTER TABLE coding_problems add constraint FKbcjrjoh98ukjd5khy6l6o7xgv foreign key (interview_question_id) references interview_questions;
        ALTER TABLE coding_problems add constraint FK7gl9w53m0cw9frfilu1n0bf8i foreign key (mock_interview_id) references mock_interviews;
        ALTER TABLE coding_replays add constraint FK4nq3wfo13xtsgg4gjj8p74c1i foreign key (coding_submission_id) references coding_submissions;
        ALTER TABLE coding_submissions add constraint FK9xltyt9xj7yl14bwq8113lf4a foreign key (coding_problem_id) references coding_problems;
        ALTER TABLE coding_submissions add constraint FKh584qj7mdmer6xj8cm60tmgiq foreign key (interview_question_id) references interview_questions;
        ALTER TABLE coding_test_cases add constraint FKjgq1dorq7bpf2wv995tw9nh71 foreign key (coding_problem_id) references coding_problems;
        ALTER TABLE company_profiles add constraint FKepa1xs3fkyb9jtavcq0t714ys foreign key (recruiter_id) references users;
        ALTER TABLE delete_account_verification add constraint FKoqq6u62yno91kv1v0o4fpunwq foreign key (user_id) references users;
        ALTER TABLE evaluation_audits add constraint FKoison6o2jo0mut890lsycdxy4 foreign key (evaluation_id) references interview_evaluations;
        ALTER TABLE evaluation_versions add constraint FKrf4ug1kl96wuioy226kvowley foreign key (evaluation_id) references interview_evaluations;
        ALTER TABLE events add constraint FKat8p3s7yjcp57lny4udqvqncq foreign key (user_id) references users;
        ALTER TABLE feedback_body_language add constraint FKadcod16edv1erjmxqyyp5eqn3 foreign key (feedback_id) references interview_feedback;
        ALTER TABLE feedback_improvements add constraint FKedmnklpi2mclab2gy2cf0t60e foreign key (feedback_id) references interview_feedback;
        ALTER TABLE feedback_missed_topics add constraint FKoml4yapjdi2ean00h5fcdh3ve foreign key (feedback_id) references interview_feedback;
        ALTER TABLE feedback_plans add constraint FKm65r0ss5ttkkq61ikg4rdo9ok foreign key (feedback_id) references interview_feedback;
        ALTER TABLE feedback_resources add constraint FKk37yi1vgxw5nxvporlefi7el2 foreign key (feedback_id) references interview_feedback;
        ALTER TABLE feedback_strengths add constraint FK2n8xvxd8oa1heq8nwt1fvb7uw foreign key (feedback_id) references interview_feedback;
        ALTER TABLE interview_architecture_metrics add constraint FK1099jimaquwpueprr2a9e3r9u foreign key (evaluation_id) references interview_evaluations;
        ALTER TABLE interview_behavior_metrics add constraint FK36coef4laoer4cmv8ma08anfy foreign key (evaluation_id) references interview_evaluations;
        ALTER TABLE interview_communication_metrics add constraint FK6tlmk1meb89ktiifcac491lvi foreign key (evaluation_id) references interview_evaluations;
        ALTER TABLE interview_competency_scores add constraint FKnb5p05lusk6fp6a6thhhfdj7y foreign key (evaluation_id) references interview_evaluations;
        ALTER TABLE interview_evaluations add constraint FK2211ctn2jd1owpyro8020lhaq foreign key (mock_interview_id) references mock_interviews;
        ALTER TABLE interview_evidence add constraint FK663mjju8x34m87ew75a1j82o6 foreign key (evaluation_id) references interview_evaluations;
        ALTER TABLE interview_feedback add constraint FK1ui0tmcx058bl1mbkjfdupllu foreign key (mock_interview_id) references mock_interviews;
        ALTER TABLE interview_hiring_decisions add constraint FKmto50xapeximvij831qd3ffuh foreign key (evaluation_id) references interview_evaluations;
        ALTER TABLE interview_improvements add constraint FKg1ekpsawq8p26dpavkynhrl40 foreign key (evaluation_id) references interview_evaluations;
        ALTER TABLE interview_interruption_logs add constraint FKiu4lpqtmlig9gf5odxthmyvod foreign key (interview_question_id) references interview_questions;
        ALTER TABLE interview_interruption_logs add constraint FKrgy3q2i5ntclrnelqfilf7x4o foreign key (mock_interview_id) references mock_interviews;
        ALTER TABLE interview_leadership_metrics add constraint FK9bw1g7cfbq6tql4fkqrbumhfg foreign key (evaluation_id) references interview_evaluations;
        ALTER TABLE interview_questions add constraint FK48ls81jyw2ed0e2ct9mivw6n6 foreign key (mock_interview_id) references mock_interviews;
        ALTER TABLE interview_reasoning add constraint FKmut0ooptutmolqcpdstpvv3gs foreign key (evaluation_id) references interview_evaluations;
        ALTER TABLE interview_recommendations add constraint FK5flld7l7orlxj89c0t76sbrqs foreign key (evaluation_id) references interview_evaluations;
        ALTER TABLE interview_records add constraint FKijhic416t5txiqtpx7d7i76l0 foreign key (user_id) references users;
        ALTER TABLE interview_schedules add constraint FKo8enekita5d4c5m8mvk2qpj4c foreign key (application_id) references job_applications;
        ALTER TABLE interview_schedules add constraint FKap8cs4mx65wxmb8euwk1lvkl7 foreign key (recruiter_id) references users;
        ALTER TABLE interview_schedules add constraint FK3m5nqj74tcpgcl34b8vqbopiu foreign key (student_id) references users;
        ALTER TABLE interview_skill_gaps add constraint FKps5p4kld508l5w2cbu1d8qeq foreign key (evaluation_id) references interview_evaluations;
        ALTER TABLE interview_technical_metrics add constraint FKi2y0uvkq6m40be3mf4e0eos7g foreign key (evaluation_id) references interview_evaluations;
        ALTER TABLE job_applications add constraint FKqt4m3c9yiioi16kwsyjrl0cpl foreign key (job_id) references jobs;
        ALTER TABLE job_applications add constraint FKqxtt5v9mi302vt7gvti7wqfky foreign key (student_id) references users;
        ALTER TABLE jobs add constraint FKtxcva9bpa232dqntnkm4k0rc foreign key (company_profile_id) references company_profiles;
        ALTER TABLE jobs add constraint FK9syuy0yp9a2c0fkr98pvxpb8m foreign key (recruiter_id) references users;
        ALTER TABLE knowledge_graph_edges add constraint FKhkw5wixpdmrye8x4vema7j6v4 foreign key (user_id) references users;
        ALTER TABLE knowledge_graph_nodes add constraint FKnjcer1ncxbb3476xm4denvn6b foreign key (user_id) references users;
        ALTER TABLE memory_events add constraint FKlen5i7ufc8x1b276mjh14eqgy foreign key (user_id) references users;
        ALTER TABLE mock_interviews add constraint FK42jfwpvkxjptd6rgcyyhpi94r foreign key (user_id) references users;
        ALTER TABLE prompt_versions add constraint FKjlgnr5mu29dpfqn56pqa55q3d foreign key (prompt_definition_id) references prompt_definitions;
        ALTER TABLE push_subscriptions add constraint FK1v577hpc7v9mdrm2uyk6kqgnl foreign key (user_id) references users;
        ALTER TABLE recruiter_notes add constraint FKcmqyulgh1a3j97awvcyvvlm2v foreign key (application_id) references job_applications;
        ALTER TABLE recruiter_notes add constraint FK5qk6kbl8jd89i6k5erwrvpvjt foreign key (recruiter_id) references users;
        ALTER TABLE recruiter_notes add constraint FKf3da4npn90kx89v062ast9r89 foreign key (student_id) references users;
        ALTER TABLE resume_builders add constraint FK9oxib6v9o2wf0dlh3h8e9vijo foreign key (user_id) references users;
        ALTER TABLE resumes add constraint FK340nuaivxiy99hslr3sdydfvv foreign key (user_id) references users;
        ALTER TABLE support_tickets add constraint FK4reg1h2465c00bg6dmqlv7ujv foreign key (user_id) references users;
        ALTER TABLE system_design_diagram_replays add constraint FKji3wnk27fsiyhuy0fwv8vwnuy foreign key (system_design_diagram_id) references system_design_diagrams;
        ALTER TABLE system_design_diagrams add constraint FK7a9h3jj4xddi728j7d2yh4lbm foreign key (interview_question_id) references interview_questions;
        ALTER TABLE system_design_diagrams add constraint FKnx89inyak9bpqqpbl4vplgcms foreign key (mock_interview_id) references mock_interviews;
        ALTER TABLE system_design_evaluations add constraint FK4ubyrg79ahsxlc4wokm22m4et foreign key (interview_question_id) references interview_questions;
        ALTER TABLE system_design_evaluations add constraint FKir5gk3d1yoywhy4rvlkc5fykv foreign key (system_design_diagram_id) references system_design_diagrams;
        ALTER TABLE system_design_scenarios add constraint FKjre9sgoqa794y7l7gs1n8kick foreign key (interview_question_id) references interview_questions;
        ALTER TABLE user_activity_logs add constraint FKci4pq8q71xm6breqdpko42wrd foreign key (user_id) references users;
        ALTER TABLE user_stats add constraint FKj277c5rcqlsvwkk3hj39e2b74 foreign key (user_id) references users;
        ALTER TABLE voice_audio_records add constraint FKjvs0lky6vdcf5rexa3egm5qv2 foreign key (interview_question_id) references interview_questions;
        ALTER TABLE voice_timeline_segments add constraint FKlgrnfjmpb2bp8wo0eysjunj5r foreign key (interview_question_id) references interview_questions;
        ALTER TABLE voice_timeline_segments add constraint FKdn9pllybaosypled3k9gq7djn foreign key (mock_interview_id) references mock_interviews;

        -- Local B-Tree Indexes on Foreign Keys (V8 Optimization)
        CREATE INDEX IF NOT EXISTS idx_chat_messages_conversation_id ON public.chat_messages (conversation_id);
        CREATE INDEX IF NOT EXISTS idx_job_applications_job_id ON public.job_applications (job_id);
        CREATE INDEX IF NOT EXISTS idx_job_applications_student_id ON public.job_applications (student_id);
        CREATE INDEX IF NOT EXISTS idx_interview_schedules_recruiter_id ON public.interview_schedules (recruiter_id);
        CREATE INDEX IF NOT EXISTS idx_interview_schedules_student_id ON public.interview_schedules (student_id);
        CREATE INDEX IF NOT EXISTS idx_coding_submissions_interview_question_id ON public.coding_submissions (interview_question_id);
        CREATE INDEX IF NOT EXISTS idx_mock_interviews_user_id ON public.mock_interviews (user_id);
        CREATE INDEX IF NOT EXISTS idx_users_supabase_uuid ON public.users (supabase_uuid);

        -- Environment-Aware Foreign Key to auth.users if auth schema is present (V8 Linkage)
        ALTER TABLE public.users ADD CONSTRAINT fk_users_supabase_auth FOREIGN KEY (supabase_uuid) REFERENCES auth.users(id) ON DELETE SET NULL;
    END IF;
END $$;
