-- Flyway Migration V13: Add AI Observability Logs, Curated Resources, and Mock Interview Snapshots

-- Create curated_resources table
CREATE TABLE IF NOT EXISTS curated_resources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    skill_keyword VARCHAR(255),
    title VARCHAR(255),
    resource_type VARCHAR(255),
    url VARCHAR(255),
    description TEXT,
    relevance INTEGER,
    difficulty VARCHAR(255),
    estimated_study_hours INTEGER,
    priority VARCHAR(255),
    category VARCHAR(255),
    prerequisites VARCHAR(255)
);

-- Create ai_observability_logs table
CREATE TABLE IF NOT EXISTS ai_observability_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mock_interview_id BIGINT REFERENCES mock_interviews(id) ON DELETE SET NULL,
    task_type VARCHAR(255),
    prompt_version VARCHAR(255),
    model_version VARCHAR(255),
    provider_name VARCHAR(255),
    temperature DOUBLE PRECISION,
    top_p DOUBLE PRECISION,
    max_tokens INTEGER,
    latency_ms BIGINT,
    prompt_tokens INTEGER,
    completion_tokens INTEGER,
    total_tokens INTEGER,
    retry_count INTEGER,
    cost_estimate DOUBLE PRECISION,
    validation_status VARCHAR(255),
    validation_errors TEXT,
    success BOOLEAN,
    created_at TIMESTAMP WITHOUT TIME ZONE
);

-- Create mock_interview_snapshots table
CREATE TABLE IF NOT EXISTS mock_interview_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mock_interview_id BIGINT NOT NULL REFERENCES mock_interviews(id) ON DELETE CASCADE,
    turn_index INTEGER,
    question_text TEXT,
    answer_text TEXT,
    evaluation_json TEXT,
    difficulty VARCHAR(255),
    knowledge_graph_snapshot_json TEXT,
    prompt_version VARCHAR(255),
    model_version VARCHAR(255),
    context_summary TEXT,
    created_at TIMESTAMP WITHOUT TIME ZONE
);

-- Indexes for performance optimization
CREATE INDEX IF NOT EXISTS idx_ai_observability_logs_mock_interview_id ON ai_observability_logs(mock_interview_id);
CREATE INDEX IF NOT EXISTS idx_mock_interview_snapshots_mock_interview_id ON mock_interview_snapshots(mock_interview_id);
CREATE INDEX IF NOT EXISTS idx_curated_resources_skill_keyword ON curated_resources(skill_keyword);
